CREATE DATABASE leaderboard;
USE leaderboard;

CREATE TABLE UserScores (
	UID VARCHAR(255) NOT NULL,
    Name VARCHAR(255) NOT NULL,
    Score INT NOT NULL,
    COUNTRY CHAR(2) NOT NULL,
    TimeStamp TIMESTAMP NOT NULL,
    PRIMARY KEY(UID)
);

-- Generate a large set of numbers
CREATE TEMPORARY TABLE Numbers (n INT);

INSERT INTO Numbers (n)
SELECT
    a.n + b.n * 10 + c.n * 100 + d.n * 1000 + e.n * 10000 + f.n * 100000 AS n
FROM
    (SELECT 0 AS n UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5) a,
    (SELECT 0 AS n UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5) b,
    (SELECT 0 AS n UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5) c,
    (SELECT 0 AS n UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5) d,
    (SELECT 0 AS n UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5) e,
    (SELECT 0 AS n UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5) f;

-- Insert fake data into UserScores
INSERT INTO UserScores (UID, Name, Score, COUNTRY, TimeStamp)
SELECT
    CONCAT('U', n) AS UID,
    CONCAT('User', n) AS Name,
    FLOOR(RAND() * 1000) AS Score,
    CASE
        WHEN RAND() < 0.2 THEN 'US'
        WHEN RAND() < 0.4 THEN 'CA'
        WHEN RAND() < 0.6 THEN 'GB'
        WHEN RAND() < 0.8 THEN 'FR'
        WHEN RAND() < 0.9 THEN 'IN'
        ELSE 'GB'
    END AS COUNTRY,
    NOW() - INTERVAL FLOOR(RAND() * 365) DAY AS TimeStamp
FROM Numbers
LIMIT 10000;

-- Drop temporary table
DROP TEMPORARY TABLE IF EXISTS Numbers;


select * from UserScores
ORDER BY UID ;
